#ifndef ASSETID_H
#define ASSETID_H

enum AssetID{
    ASSET_TEXTURE_SQUARE,
    ASSET_TEXTURE_SQUARE_GRAY,
    ASSET_TEXTURE_CURSOR,
    ASSET_TEXTURE_CROSS,
    ASSET_TEXTURE_CIRCLE,
    ASSET_TEXTURE_BACKGROUND,
    ASSET_TEXTURE_HEART_GREEN,
    ASSET_TEXTURE_HEART_RED,
    ASSET_FONT_ATLAS_GABATO,
    ASSET_SOUND_CLICK
};
#endif
