#ifndef ASSETID_H
#define ASSETID_H

enum AssetID{
    ASSET_TEXTURE_SQUARE,
    ASSET_TEXTURE_SQUARE_GRAY,
    ASSET_TEXTURE_CURSOR,
    ASSET_TEXTURE_CROSS,
    ASSET_TEXTURE_CIRCLE,
    ASSET_TEXTURE_BACKGROUND,
    ASSET_TEXTURE_GREEN_RED_BACKGROUND,
    ASSET_FONT_ATLAS_GABATO_WHITE_24,
    ASSET_FONT_ATLAS_GABATO_WHITE_64,
    ASSET_FONT_ATLAS_GABATO_WHITE_124,
    ASSET_AUDIO_CLICK
};
#endif
